ci: Fix supabase secret

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,13 +1,22 @@
 name: Main Flow
 
 on:
-  push:
+  pull_request:
     branches: ["main"]
 
 jobs:
   build:
     runs-on: ubuntu-latest
+    env:
+      VITE_SUPABASE_KEY: ${{secrets.VITE_SUPABASE_KEY}}
+
     steps:
+      - name: Check secrets
+        if: ${{ env.VITE_SUPABASE_KEY == '' }}
+        run: |
+          echo 'Couldn't find the secret VITE_SUPABASE_KEY'
+          exit 1
+
       - name: Checkout repo
         uses: actions/checkout@v4
 
